### ISSUE TITLE
Regarding Security Vulnerability - Leap Cosmos Wallet

### ISSUE THREAD

**Issue by imnarendrabhati** [leapwallet/leap-keychain#30]
Dear Team,

May I know where to report Security Vulnerability In Leap Cosmos Android Wallet, and do you have any Bug Bounty Program for the same?

My X Profile is https://x.com/imnarendrabhati

**Comment by imnarendrabhati** [comment]
May I get a response on this please?

**Comment by baryon2** [comment]
@imnarendrabhati please report this on [security@leapwallet.io](mailto:security@leapwallet.io).
